config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "staff_constraint"
require "googleauth"

Rails.application.routes.draw do
  mount Peek::Railtie => "/peek"
  mount ActionCable.server => "/cable"

  root to: "pages#home"

  get "/assistant", to: "pages#assistant"
  get "/help/(:article_name)", to: "pages#help", as: "help"
  get "/home", to: "pages#home"

  get  "/login",  to: "sessions#new",     as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"

  get  "/login/oauth/authorize", to: "oauth#authorize"
  post "/login/oauth/access_token", to: "oauth#access_token"

  post "/auth/lti/launch",          to: "sessions#lti_launch"
  get "/auth/lti/setup",            to: "sessions#lti_setup"
  get "/auth/lti/failure",          to: "sessions#lti_failure"
  match "/auth/:provider/callback", to: "sessions#create",        via: %i[get post]
  match "/auth/failure",            to: "sessions#failure",       via: %i[get post]

  match "/google_classroom/oauth2_callback", to: Google::Auth::WebUserAuthorizer::CallbackApp, via: :all

  get "/a/:short_key", to: "short_url#assignment_invitation",       as: "assignment_invitation_short"
  get "/g/:short_key", to: "short_url#group_assignment_invitation", as: "group_assignment_invitation_short"

  get "/autocomplete/github_repos", to: "autocomplete#github_repos"

  get "/boom", to: "site#boom_town"
  get "/boom/sidekiq", to: "site#boom_sidekiq"

  scope "github", as: "github" do
    constraints user_agent: %r{\AGitHub-Hookshot/\w+\z}, format: "json" do
      post :hooks, to: "hooks#receive"
    end
  end

  resources :assignment_invitations, path: "assignment-invitations", only: [:show] do
    member do
      patch :accept
      get   :setup
      post  :create_repo
      get   :progress
      get   :success
      patch :join_roster
    end
  end

  resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :setup
      post  :create_repo
      get   :progress
      get   :successful_invitation, path: :success
      patch :join_roster
    end
  end

  scope path_names: { edit: "settings" } do
    resources :organizations, path: "classrooms" do
      collection do
        get :search
      end

      member do
        get   :link_lms
        get   :invite
        get   :new_assignment, path: "new-assignment"
        get   :setup
        patch :setup_organization
        get   "settings/invitations", to: "organizations#invitation"
        get   "settings/teams",       to: "organizations#show_groupings"
        delete "users/:user_id",      to: "organizations#remove_user", as: "remove_user"

        resource :roster, only: %i[show new create], controller: "orgs/rosters" do
          patch :link
          patch :unlink
          patch :delete_entry
          patch :edit_entry
          patch :add_students
          patch :remove_organization
          patch :import_from_google_classroom
          patch :sync_google_classroom
          get   :import_from_lms
        end

        resource :lti_configuration, controller: "orgs/lti_configurations" do
          get :info
          get :autoconfigure
          get :complete
        end

        scope :google_classrooms do
          root "orgs/google_classroom_configurations#index", as: :google_classrooms_index
          get  "search", to: "orgs/google_classroom_configurations#search", as: "google_classrooms_search"
          post "create", to: "orgs/google_classroom_configurations#create", as: "google_classrooms_create"
          delete "delete", to: "orgs/google_classroom_configurations#destroy", as: "google_classrooms_delete"
        end
      end

      resources :groupings, only: %i[show edit update] do
        resources :groups, only: [:show] do
          member do
            patch "/memberships/:user_id", to: "groups#add_membership", as: "add_membership"
            delete "/memberships/:user_id", to: "groups#remove_membership", as: "remove_membership"
          end
        end
      end

      resources :assignments do
        resources :assignment_repos, only: [:show], controller: "orgs/assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
        get :assistant, on: :member
        member do
          post :toggle_invitations
        end
      end

      resources :group_assignments, path: "group-assignments" do
        resources :group_assignment_repos, only: [:show], controller: "orgs/group_assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
        get :assistant, on: :member
        member do
          post :toggle_invitations
        end
      end
    end
  end

  resources :videos, only: [:index]

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => "/sidekiq"
      mount Flipper::UI.app(GitHubClassroom.flipper) => "/flipper", as: "flipper"
    end

    root "resources#index", as: :root
    get "/resource_search", to: "resources#search"

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: "classrooms", only: [:show] do
      member do
        delete "/users/:user_id", to: "organizations#remove_user", as: "remove_user"
        post :ensure_webhook_is_active
      end
    end

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: %i[show destroy]
    resources :assignments,            only: [:show]

    resources :deadlines, only: [:show]

    resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show]
    resources :group_assignment_repos,       path: "group-assignment-repos",       only: %i[show destroy]
    resources :group_assignments,            path: "group-assignments",            only: [:show]

    resources :groupings, only: %i[show destroy]
    resources :groups,    only: %i[show destroy]
  end

  namespace :api, defaults: { format: :json } do
    scope :internal do
      scope "classrooms/:organization_id" do
        resources :assignments, only: %i[index show] do
          resources :assignment_repos, only: [:index] do
            get "/clone_url", to: "assignment_repos#clone_url"
          end
        end
        resources :group_assignments, path: "group-assignments", only: %i[index show] do
          resources :group_assignment_repos, path: "group-assignment-repos", only: [:index] do
            get "/clone_url", to: "group_assignment_repos#clone_url"
          end
        end
      end
      get "/user", to: "users#authenticated_user"
    end
  end
end

app/views/shared/_commit_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'git-commit',
  octicon_class: 'neutral',
  text: text,
  hover_text: 'View commits',
  url: url %>

app/views/shared/_failed_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'x',
  octicon_class: 'failed',
  text: text
%>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash-application container-lg">
    <%= content_tag :div, class: "flash #{primer_class_for(type)}" do %>
      <span class="flash-close js-flash-close">
        <%= octicon('x') %>
      </span>
      <%= sanitize(message) %>
    <% end %>
  </div>
<% end %>

app/views/shared/_form_error.html.erb
  <dd class="error"><%= errors %></dd>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="container-lg d-md-flex flex-items-center flex-justify-between p-responsive py-3">
    <%= link_to(image_tag('logo@2x.png', class: 'site-logo', alt: 'GitHub for Classrooms'), (logged_in? ? organizations_path : root_path), class: 'd-block text-center mb-2 mb-md-0') %>

    <nav class="site-nav d-sm-flex flex-wrap flex-content-start flex-justify-center">
      <%= link_to "GitHub Education", 'https://education.github.com', target: '_blank', class: 'd-block text-center mx-sm-3 mb-2 mb-sm-0' %>

      <ul class="list-style-none d-flex flex-justify-center">
        <% if logged_in? %>
          <li class="ml-3">
            <details class="dropdown details-reset details-overlay d-inline-block">
              <summary aria-haspopup="true">
                <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
                <div class="dropdown-caret mt-1"></div>
              </summary>

              <div role="menu" class="dropdown-menu dropdown-menu-sw mt-2" style="width: 180px">
                <%= link_to current_user.github_user.html_url, class: "dropdown-item", role: "menuitem" do %>
                  <%= t("views.shared.signed_in_as") %> <strong class="d-block"><%= current_user.github_user.login %></strong>
                <% end %>

                <div role="none" class="dropdown-divider"></div>

                <%= link_to t("views.shared.your_classrooms"), organizations_path, class: "dropdown-item", role: "menuitem" %>
                <%= link_to t("views.shared.community_discussion"), "https://education.github.com/forum", class: "dropdown-item", role: "menuitem" %>
                <%= link_to t("views.shared.report_bug"), 'https://github.com/education/classroom/issues', class: "dropdown-item", role: "menuitem" %>
                <%= link_to t("views.shared.changelog"), 'https://github.com/education/classroom/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc', class: "dropdown-item", role: "menuitem", target: '_blank' %>

                <div role="none" class="dropdown-divider"></div>

                <%= link_to t("views.shared.help"), help_path, class: "dropdown-item", role: 'menuitem' %>
                <%= link_to t("views.shared.sign_out"), logout_path, method: :post, class: "dropdown-item dropdown-signout", role: 'menuitem' %>
              </div>
            </details>
          </li>
        <% else %>
          <li class="ml-3"><%= link_to t('views.shared.sign_in'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_invitation.html.erb
<dt class=<%= mobile? ? "mobile-invitation-content" : "desktop-invitation-content" %>>
  <%= check_box_tag 'invitations_enabled',true, (@assignment.nil? ? @group_assignment.invitations_enabled : @assignment.invitations_enabled),
    onchange: "$(this).data('params', 'invitations_enabled=' + this.checked);showLoadingIndicator(true);showCheckmark(false);",
    data: {
      remote: true,
      url: url_for(action: :toggle_invitations, id: (@assignment.nil? ? @group_assignment.slug : @assignment.slug)),
      method: "POST"
    } %>
  <label class="pl-1">Enable assignment invitation URL <span class="tooltipped tooltipped-no-delay tooltipped-n tooltipped-multiline d-inline-block pl-1" style="bottom: 3px" aria-label="While enabled, students will be able to accept and access this assignment. When you no longer want anyone to access this assignment, uncheck to deactivate the invitation link."><%= octicon 'info' %></span></label>
  <span class="text-green"><%= octicon 'check', height: 16, id: "checkmark", style: "display: none; padding-bottom: 3px;" %></span>
  <%= image_tag 'octocat-spinner-128.gif', width: 13, height: 13, class: 'spinner', id: "loading-indicator", style: "display:none" %>
  <div class="input-group input-block pt-2">
    <%= render partial: "shared/invitations/clipboard_form", locals: local_assigns %>
  </div>
  <p class="note pt-1 mb-4">
    <%= t('views.shared.share_invite_url') %>
  </p>
</dt>

app/views/shared/_invitation_header.html.erb
<header class="site-header">
  <div class="container-lg d-md-flex flex-items-center flex-justify-between p-responsive py-3">
    <%= link_to(image_tag('logo@2x.png', class: 'site-logo', alt: 'GitHub for Classrooms'), (logged_in? ? organizations_path : root_path), class: 'd-block text-center mb-2 mb-md-0') %>

    <nav class="site-nav d-sm-flex flex-wrap flex-content-start flex-justify-center">
      <%= link_to "GitHub Education", 'https://education.github.com', target: '_blank', class: 'd-block text-center mx-sm-3 mb-2 mb-sm-0' %>

      <ul class="list-style-none d-flex flex-justify-center">
        <li class="mx-3">
          <%= link_to 'https://education.github.com/forum', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.community_discussion') do %>
            <%= octicon 'comment-discussion' %>
          <% end %>
        </li>

        <li class="mx-3">
          <%= link_to 'https://github.com/education/classroom/issues', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.report_bug') do %>
            <%= octicon 'bug' %>
          <% end %>
        </li>

        <li class="mx-3">
          <%= link_to 'https://github.com/education/classroom/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc', target: '_blank', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.changelog') do %>
            <%= octicon 'git-pull-request' %>
          <% end %>
        </li>

        <li class="mx-3">
          <%= link_to help_path, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.help') do %>
            <%= octicon 'question' %>
          <% end %>
        </li>

        <li class="mx-3">
          <%= link_to current_user.github_user.html_url, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.view_gh_profile') do %>
            <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
          <% end %>
        </li>

        <li class="ml-3">
          <%= link_to logout_path, method: :post, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.sign_out') do %>
            <%= octicon 'sign-out' %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_members_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'person',
  octicon_class: 'neutral',
  text: text,
  hover_text: 'View members',
  url: url %>

app/views/shared/_pagination.html.erb
<% if collection.next_page || collection.prev_page %>
  <div class="paginate-container container">
    <%= paginate collection, param_name: (local_assigns[:param_name] || :page) %>
  </div>
<% end %>

app/views/shared/_repo_detail.html.erb
<% # optional params    %>
<% url           ||= '' %>
<% hover_text    ||= '' %>

<% if url.present? %>
  <a class="repo-detail-item <%= 'tooltipped tooltipped-n' if hover_text.present? %>" aria-label="<%= hover_text %>" href="<%= url %>" target='_blank'>
    <span class="submission-icon-container">
      <%= octicon octicon_name, height: 20, class: octicon_class %>
    </span>
    <span class='text-muted'><%= text %></span>
  </a>
<% else %>
    <span class="repo-detail-item <%= 'tooltipped tooltipped-n' if hover_text.present? %>" aria-label="<%= hover_text %>">
      <span class='submission-icon-container'>
        <%= octicon octicon_name, height: 20, class: octicon_class %>
      </span>
      <span class='text-muted'><%= text %></span>
    </span>
<% end %>

app/views/shared/_roster_tab_script.html.erb
<script>
  if(typeof selectTab === "function"){
    setTabOnLoad();
  }else{
    document.addEventListener("DOMContentLoaded", function(_event) {
      setTabOnLoad();
    });
  }
</script>

app/views/shared/_select_menu.html.erb
<% remote = local_assigns.fetch(:remote, false) %>

<div class="select-menu">
  <button class="btn ml-2 select-menu-button" aria-expanded="false" tabindex="0">
    <i><%= title %></i>
    <span class="selected-option"><%= selected_option %></span>
  </button>
  <div class="select-menu-modal-holder">
    <div class="select-menu-modal">
      <div class="select-menu-header" tabindex="-1">
        <%= octicon 'x', class: "select-menu-close-button" %>
        <span class="select-menu-title"><%= title %></span>
      </div>
      <div class="select-menu-list">
        <% options.each_with_index do |option, i| %>
          <% conditional_selected_class = "selected" if option == selected_option %>

          <%= link_to option_links[i], class: "select-menu-item #{conditional_selected_class}", remote: remote do %>
            <% show_or_hide_class = "v-hidden" unless option == selected_option %>

            <%= octicon 'check', class: "select-menu-item-icon #{show_or_hide_class}" %>
            <span class="select-menu-item-text"><%= option %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_submission_failed_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'stop',
  octicon_class: 'failed',
  text: 'Not Submitted' %>

app/views/shared/_unlinked_blank_slate.html.erb
<div class="blankslate">
  <h3><%= t("views.rosters.blank_slate_header") %></h3>
</div>